# Generated by Django 5.1.4 on 2024-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.CharField(default='default_answer', max_length=255),
        ),
    ]
