# Generated by Django 5.1.4 on 2024-12-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_remove_problem_answer_problem_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='problem',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
