# Generated by Django 5.1.4 on 2024-12-31 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'problem')},
        ),
    ]
