# Generated by Django 5.1.4 on 2024-12-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_correct_answer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='problems.problem'),
        ),
    ]
