# Generated by Django 5.1.4 on 2024-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_solved_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5-сынып'), (6, '6-сынып'), (7, '7-сынып'), (8, '8-сынып'), (9, '9-сынып'), (10, '10-сынып'), (11, '11-сынып')], null=True, verbose_name='Сынып'),
        ),
    ]
