version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: math_week
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 123456789m
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    # command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: math_week
      DB_USER: user1
      DB_PASSWORD: 123456789m
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
